Notes for final submission:
Accuracy has been improved to 75% from 50% by decreasing the number of targets from 5 to 3.
Ngrok is still being used since no other hosting service is viable for this. Ngrok throws errors from time to time as the free version is supporting only 20 external instructions per minute, Though it functions much better than before after disabling stylsheets. Precaution must be taken not to enter too many responses in a minute.
*it is recommended to run on colab: https://colab.research.google.com/drive/1JAxfDUPnHEJqqTTS_nKB9d8hAMGyTTuj?usp=sharing

In [0]:
import pandas as pd

In [0]:
df = pd.read_excel('https://github.com/SGE616/xcelerator_Sentiment_analysis_project/raw/master/Datafiniti_Hotel_Reviews.xlsx')

In [3]:
df.head()

id  ...                                           websites
0  AVwc252WIN2L1WUfpqLP  ...                      http://www.ranchovalencia.com
1  AVwc252WIN2L1WUfpqLP  ...                      http://www.ranchovalencia.com
2  AVwc252WIN2L1WUfpqLP  ...                      http://www.ranchovalencia.com
3  AVwdOclqIN2L1WUfti38  ...  http://www.starwoodhotels.com/alofthotels/prop...
4  AVwdOclqIN2L1WUfti38  ...  http://www.starwoodhotels.com/alofthotels/prop...

[5 rows x 25 columns]

In [0]:
rev = df[['reviews.title','reviews.text','reviews.rating']]

In [0]:
def round_of_rating(number):
    if number < 1.67:
      rating = 1
    elif number >= 1.67 and number < 3.33:
      rating = 2
    elif number >= 3.33:
      rating = 3
    return rating

In [6]:
rev.loc[:,'reviews.rating'] = rev.loc[:,'reviews.rating'].copy().apply(round_of_rating)

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [7]:
cnts = rev.groupby('reviews.rating').count()
cnts['reviews.rating'] = cnts.index
cnts

reviews.title  reviews.text  reviews.rating
reviews.rating                                             
1                         588           588               1
2                        1891          1890               2
3                        7520          7521               3

In [0]:
label = {1:'Bad',2:'Neutral',3:'Good'}

In [0]:
from plotly.offline import iplot
import plotly.graph_objs as go

In [0]:
counts = [go.Bar(x=cnts['reviews.rating'],y=cnts['reviews.title'],)]

In [0]:
fig = {
        'data': counts,
        'layout': dict(
            xaxis={'title': 'Sentiment','tickvals' : [1,2,3], 'ticktext': ['Bad','Neutral','Good']},
            yaxis={'title': 'Number'},
				title = 'Sentiment Break-up'
        )
    }

In [36]:
iplot(fig)

In [10]:
counts

[Bar({
     'x': array([1, 2, 3]), 'y': array([ 588, 1891, 7520])
 })]

In [0]:
import re

In [0]:
def cleanTxt(text):
    text = str(text)
    text = text.lower()
    text = re.sub(r'[;:!\\"\'()\[\]]',"", text)
    text = re.sub(r'(<br\s*/><br\s*/>)|(\-)|(\/)'," ", text)
    return text

In [13]:
rev.loc[:,'reviews.title']=rev.loc[:,'reviews.title'].apply(cleanTxt)
rev.loc[:,'reviews.text']=rev.loc[:,'reviews.text'].apply(cleanTxt)

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [14]:
rev.head()

reviews.title  ... reviews.rating
0               best romantic vacation ever  ...              3
1                      sweet sweet serenity  ...              3
2           amazing property and experience  ...              3
3  never again...beware, if you want sleep.  ...              2
4                      always great stay...  ...              3

[5 rows x 3 columns]

In [0]:
from nltk.stem import PorterStemmer 
from nltk.tokenize import word_tokenize

In [0]:
ps = PorterStemmer() 

In [0]:
def stemmer(para):
    w = word_tokenize(para)
    l = [ps.stem(j) for j in w]
    link = ' '
    s = link.join(l)
    return s

In [18]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [37]:
rev.loc[:,'reviews.title'] = rev.loc[:,'reviews.title'].apply(stemmer)
rev.loc[:,'reviews.text'] = rev.loc[:,'reviews.text'].apply(stemmer)

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [38]:
rev.head()

reviews.title  ... reviews.rating
0                       best romant vacat ever  ...              3
1                            sweet sweet seren  ...              3
2                     amaz properti and experi  ...              3
3  never again ... bewar , if you want sleep .  ...              2
4                         alway great stay ...  ...              3

[5 rows x 3 columns]

In [0]:
from textblob import TextBlob

In [0]:
def n_grams(text):
  return TextBlob(text).ngrams(n=3)

In [41]:
rev['ngrams'] = rev['reviews.text'].apply(n_grams)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [42]:
rev.head()

reviews.title  ...                                             ngrams
0                       best romant vacat ever  ...  [[our, experi, at], [experi, at, rancho], [at,...
1                            sweet sweet seren  ...  [[amaz, place, everyon], [place, everyon, wa],...
2                     amaz properti and experi  ...  [[we, book, a], [book, a, 3], [a, 3, night], [...
3  never again ... bewar , if you want sleep .  ...  [[current, in, bed], [in, bed, write], [bed, w...
4                         alway great stay ...  ...  [[i, live, in], [live, in, md], [in, md, and],...

[5 rows x 4 columns]

In [43]:
!pip install vaderSentiment

In [0]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

In [0]:
sid = SentimentIntensityAnalyzer()

In [0]:
def pol_score(text):
  return sid.polarity_scores(text)['compound']

In [47]:
rev['polarity_score'] = rev['reviews.text'].apply(pol_score)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [48]:
rev.head()

reviews.title  ... polarity_score
0                       best romant vacat ever  ...         0.8910
1                            sweet sweet seren  ...         0.8225
2                     amaz properti and experi  ...         0.9559
3  never again ... bewar , if you want sleep .  ...         0.0000
4                         alway great stay ...  ...         0.8225

[5 rows x 5 columns]

In [0]:
import numpy as np
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.model_selection import train_test_split 

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [0]:
text_based = rev[['reviews.title','reviews.text']] #storing the text based attributes

In [52]:
text_based.head()

reviews.title                                       reviews.text
0                       best romant vacat ever  our experi at rancho valencia wa absolut perfe...
1                            sweet sweet seren  amaz place . everyon wa extrem warm and welcom...
2                     amaz properti and experi  we book a 3 night stay at rancho valencia to p...
3  never again ... bewar , if you want sleep .  current in bed write thi for the past hr 1 2 t...
4                         alway great stay ...  i live in md and the aloft is my home away fro...

In [53]:
text_based['all text'] = text_based['reviews.title'] + ' ' + text_based['reviews.text']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [54]:
text_based

reviews.title  ...                                           all text
0                          best romant vacat ever  ...  best romant vacat ever our experi at rancho va...
1                               sweet sweet seren  ...  sweet sweet seren amaz place . everyon wa extr...
2                        amaz properti and experi  ...  amaz properti and experi we book a 3 night sta...
3     never again ... bewar , if you want sleep .  ...  never again ... bewar , if you want sleep . cu...
4                            alway great stay ...  ...  alway great stay ... i live in md and the alof...
...                                           ...  ...                                                ...
9995                     pictur window ocean view  ...  pictur window ocean view it is hard for me to ...
9996                    clean , comfort and quiet  ...  clean , comfort and quiet i live close by , an...
9997                                 pass through  ...  pass through roll in 1130 laid out head down w...
9998                                      terribl  ...  terribl absolut terrible..i wa told i wa be gi...
9999                                         pold  ...  pold filthi , outdat , noisi neighbour , but t...

[10000 rows x 3 columns]

In [0]:
X = text_based['all text']
y = rev['reviews.rating']

In [0]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.3,random_state=42)

In [0]:
from sklearn.pipeline import Pipeline

In [0]:
#using Naive Bayes first
from sklearn.naive_bayes import MultinomialNB

In [0]:
NB = Pipeline([('tfidf',TfidfVectorizer()),('model',MultinomialNB())])

In [60]:
NB.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('model',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [0]:
NB_pred = NB.predict(X_test)

In [62]:
print(confusion_matrix(y_test,NB_pred))
print(classification_report(y_test,NB_pred))
print(accuracy_score(y_test,NB_pred))

[[   0    5  160]
 [   0    5  605]
 [   0    2 2223]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       165
           2       0.42      0.01      0.02       610
           3       0.74      1.00      0.85      2225

    accuracy                           0.74      3000
   macro avg       0.39      0.34      0.29      3000
weighted avg       0.64      0.74      0.64      3000

0.7426666666666667


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning:

Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.



In [0]:
#using Decision trees
from sklearn.tree import DecisionTreeClassifier

In [0]:
tree = Pipeline([('tfidf',TfidfVectorizer()), ('model',DecisionTreeClassifier())])

In [65]:
tree.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='...
                                 tokenizer=None, use_idf=True,
                                 vocabulary=None)),
                ('model',
                 DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                        criterion='gini', max_depth=None,
             

In [0]:
tree_pred = tree.predict(X_test)

In [67]:
print(confusion_matrix(y_test,tree_pred))
print(classification_report(y_test,tree_pred))
print(accuracy_score(y_test,tree_pred))

[[  56   64   45]
 [  58  241  311]
 [  35  248 1942]]
              precision    recall  f1-score   support

           1       0.38      0.34      0.36       165
           2       0.44      0.40      0.41       610
           3       0.85      0.87      0.86      2225

    accuracy                           0.75      3000
   macro avg       0.55      0.54      0.54      3000
weighted avg       0.74      0.75      0.74      3000

0.7463333333333333


In [0]:
#using random forest
from sklearn.ensemble import RandomForestClassifier

In [0]:
rfc = Pipeline([('tfidf',TfidfVectorizer()), ('model',RandomForestClassifier())])

In [70]:
rfc.fit(X_train,y_train)

Pipeline(memory=None,
         steps=[('tfidf',
                 TfidfVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.float64'>,
                                 encoding='utf-8', input='content',
                                 lowercase=True, max_df=1.0, max_features=None,
                                 min_df=1, ngram_range=(1, 1), norm='l2',
                                 preprocessor=None, smooth_idf=True,
                                 stop_words=None, strip_accents=None,
                                 sublinear_tf=False,
                                 token_pattern='...
                 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=None, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None

In [0]:
rfc_pred = rfc.predict(X_test)

In [72]:
print(confusion_matrix(y_test,rfc_pred))
print(classification_report(y_test,rfc_pred))
print(accuracy_score(y_test,rfc_pred))

[[  11   39  115]
 [   3   53  554]
 [   0    4 2221]]
              precision    recall  f1-score   support

           1       0.79      0.07      0.12       165
           2       0.55      0.09      0.15       610
           3       0.77      1.00      0.87      2225

    accuracy                           0.76      3000
   macro avg       0.70      0.38      0.38      3000
weighted avg       0.73      0.76      0.68      3000

0.7616666666666667


In [73]:
# How to run a Dash app in Google Colab

## Requirements

### Install ngrok
!wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
!unzip ngrok-stable-linux-amd64.zip

!pip install dash #for the dashboard

--2020-05-24 05:29:56--  https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
Resolving bin.equinox.io (bin.equinox.io)... 34.205.198.58, 34.196.154.11, 52.5.95.18, ...
Connecting to bin.equinox.io (bin.equinox.io)|34.205.198.58|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13773305 (13M) [application/octet-stream]
Saving to: ‘ngrok-stable-linux-amd64.zip.2’

ngrok-stable-linux- 100%[===================>]  13.13M  57.9MB/s    in 0.2s    

2020-05-24 05:29:57 (57.9 MB/s) - ‘ngrok-stable-linux-amd64.zip.2’ saved [13773305/13773305]

Archive:  ngrok-stable-linux-amd64.zip
replace ngrok? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [0]:
### Run ngrok to tunnel Dash app port 8050 to the outside world. 
### This command runs in the background.
get_ipython().system_raw('./ngrok http 8050 &')

In [92]:
### Get the public URL where you can access the Dash app. Copy this URL.
! curl -s http://localhost:4040/api/tunnels | python3 -c \
    "import sys, json; print(json.load(sys.stdin)['tunnels'][0]['public_url'])"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


In [0]:
#reading the app.py file from github repo
import urllib
url = "https://raw.githubusercontent.com/SGE616/xcelerator_Sentiment_analysis_project/master/app.py"
file = urllib.request.urlopen(url)
fwrite = open('apprun.py',mode='w+')
for line in file:
  decoded_line = line.decode("utf-8")
  fwrite.writelines(decoded_line)
fwrite.close()

In [94]:
!python apprun.py

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

apprun.py:52: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-

In [0]:
#snippet of what the app does
def update_figure(review):
    review = cleanTxt(review)
    review = stemmer(review)
    n_prd = NB.predict([review])
    t_prd = tree.predict([review])
    r_prd = rfc.predict([review])
    estimation = [go.Bar(x=['NaiveBayes','Decision tree','Random forest'],y=[n_prd[0],t_prd[0],r_prd[0]])]

    return {
        'data': estimation,
        'layout': dict(
            xaxis={'title': 'Model used'},
            yaxis={'title': 'Prediction','tickvals' : [1,2,3], 'ticktext': ['Bad','Neutral','Good']},
				title = 'Review Prediction'
        )
    }

In [0]:
fig = update_figure("Horrible experience! would not recommend")
  

In [100]:
iplot(fig)